# Generated by Django 2.2.3 on 2019-07-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='added_list',
            field=models.TextField(max_length=2050),
        ),
    ]
